version: '3'

services:
  app:
    image: cop-app
    networks:
      - traefik-public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.cop-web-http.rule=Host(`cm.vijaystroup.com`)
        - traefik.http.routers.cop-web-http.entrypoints=http
        - traefik.http.routers.cop-web-http.middlewares=https-redirect
        - traefik.http.routers.cop-web-https.rule=Host(`cm.vijaystroup.com`)
        - traefik.http.routers.cop-web-https.entrypoints=https
        - traefik.http.routers.cop-web-https.tls=true
        - traefik.http.routers.cop-web-https.tls.certresolver=le
        - traefik.http.services.cop-web.loadbalancer.server.port=80

networks:
  traefik-public:
    external: true
